// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojehfcpicmurzafhkqjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qZWhmY3BpY211cnphZmhrcWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMDk5NTcsImV4cCI6MjA2MTU4NTk1N30.8P3rN7bkzpSq_vZ-ZuMf9AeP-BBTRpFXBaUp9dpStNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);